name: Android CI

on:
  pull_request: #develop branch에 PR을 보낼 때 실행
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

      #gradle wrappper 파일 실행 권한 주기
    - name: Grant execute permission for gradlew 
      run:  |
        cd ./android
        chmod +x gradlew
    
          #gradle 빌드 실행
    - name: Test with Gradle
      run:  |
        yarn install
        cd ./android
        ./gradlew --info test

      #gradle 빌드 실행
    # - name: Build with Gradle
    #   run:  |
    #     yarn install
    #     cd ./android
    #     ./gradlew build
